services:
  # Infrastructure
  my-people-localstack:
    environment:
      - SERVICES=cloudwatch,iam,logs,sts
      - DEBUG=${DEBUG:-0}
    ports:
      - "4566:4566"
      - "4510-4559:4510-4559"

  # Services
  my-people-client-web:
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
    ports:
      - "3000:80"

  my-people-gateways-web:
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
      - ASPNETCORE_HTTP_PORTS=5000
    ports:
      - "5000:5000"

  my-people-identity-web:
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
      - ASPNETCORE_HTTP_PORTS=4000
    ports:
      - "4000:4000"

  my-people-services-images-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
      - ASPNETCORE_HTTP_PORTS=5010
    ports:
      - "5010:5010"

  my-people-services-posts-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
      - ASPNETCORE_HTTP_PORTS=5020
    ports:
      - "5020:5020"
