services:
  # Infrastructure
  my-people-localstack:
    environment:
      - SERVICES=cloudwatch,ec2,iam,lambda,logs,s3,sqs,sts
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - DEBUG=${DEBUG:-0}
      - LAMBDA_DOCKER_FLAGS='-p 19891:19891'
    ports:
      - "4566:4566"
      - "4510-4559:4510-4559"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

  # Services
  my-people-client-web:
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
      - Logging__LogLevel__Default=Debug
      - Logging__LogLevel__Microsoft.AspNetCore=Debug
    ports:
      - "3000:80"

  my-people-gateways-web:
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
      - ASPNETCORE_HTTP_PORTS=5000
      - Logging__LogLevel__Default=Debug
      - Logging__LogLevel__Microsoft.AspNetCore=Debug
    ports:
      - "5000:5000"

  my-people-identity-web:
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
      - ASPNETCORE_HTTP_PORTS=4000
      - Logging__LogLevel__Default=Debug
      - Logging__LogLevel__Microsoft.AspNetCore=Debug
    ports:
      - "4000:4000"

  my-people-services-images-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
      - ASPNETCORE_HTTP_PORTS=5010
      - Logging__LogLevel__Default=Debug
      - Logging__LogLevel__Microsoft.AspNetCore=Debug
    ports:
      - "5010:5010"

  my-people-services-posts-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
      - ASPNETCORE_HTTP_PORTS=5020
      - Logging__LogLevel__Default=Debug
      - Logging__LogLevel__Microsoft.AspNetCore=Debug
    ports:
      - "5020:5020"
