services:
  # Services
  my-people-client-web:
    container_name: my-people-client-web
    image: my-people-client-web
    build:
      context: .
      dockerfile: src/Clients/MyPeople.Client.Web/Dockerfile
    networks:
      - my-people-network

  my-people-gateways-web:
    container_name: my-people-gateways-web
    image: my-people-gateways-web
    build:
      context: .
      dockerfile: src/Gateways/MyPeople.Gateways.Web/Dockerfile
    depends_on:
      - my-people-identity-web
      - my-people-services-images-api
      - my-people-services-posts-api
    networks:
      - my-people-network

  my-people-identity-web:
    container_name: my-people-identity-web
    image: my-people-identity-web
    build:
      context: .
      dockerfile: src/Identity/MyPeople.Identity.Web/Dockerfile
    networks:
      - my-people-network

  my-people-services-images-api:
    container_name: my-people-services-images-api
    image: my-people-services-images-api
    build:
      context: .
      dockerfile: src/Services/Images/MyPeople.Services.Images.API/Dockerfile
    networks:
      - my-people-network

  my-people-services-posts-api:
    container_name: my-people-services-posts-api
    image: my-people-services-posts-api
    build:
      context: .
      dockerfile: src/Services/Posts/MyPeople.Services.Posts.API/Dockerfile
    networks:
      - my-people-network

networks:
  my-people-network:
    driver: bridge
